In [54]:
import pandas as pd
import numpy as np

# pandas

In [103]:
df = pd.read_csv('music.csv')
df

Artist Genre  Listeners       Plays
0  billie Holiday  Jazz    1300000  27000000.0
1    Jimi Hendrix  Rock    2700000  70000000.0
2     Miles Davis  Jazz    1500000  48000000.0
3             SIA   Pop    2000000  74000000.0
4    Jimi Hendrix  Rock    2700000         NaN

In [104]:
df['Artist']

0    billie Holiday
1      Jimi Hendrix
2       Miles Davis
3               SIA
4      Jimi Hendrix
Name: Artist, dtype: object

In [105]:
# select one or multiple rows 
df[1:3]

Artist Genre  Listeners       Plays
1  Jimi Hendrix  Rock    2700000  70000000.0
2   Miles Davis  Jazz    1500000  48000000.0

In [106]:
# Select any slice of the table using a both column label and row numbers using loc 
# (but here it would be inclusive of both bounding row numbers)
df.loc[1:3, ['Artist']]

Artist
1  Jimi Hendrix
2   Miles Davis
3           SIA

In [107]:
df[df['Genre'] == 'Jazz']

Artist Genre  Listeners       Plays
0  billie Holiday  Jazz    1300000  27000000.0
2     Miles Davis  Jazz    1500000  48000000.0

In [108]:
df[df['Listeners'] > 1800000]

Artist Genre  Listeners       Plays
1  Jimi Hendrix  Rock    2700000  70000000.0
3           SIA   Pop    2000000  74000000.0
4  Jimi Hendrix  Rock    2700000         NaN

In [109]:
df2 = df.fillna(0)
df2

Artist Genre  Listeners       Plays
0  billie Holiday  Jazz    1300000  27000000.0
1    Jimi Hendrix  Rock    2700000  70000000.0
2     Miles Davis  Jazz    1500000  48000000.0
3             SIA   Pop    2000000  74000000.0
4    Jimi Hendrix  Rock    2700000         0.0

In [110]:
df.dropna()

Artist Genre  Listeners       Plays
0  billie Holiday  Jazz    1300000  27000000.0
1    Jimi Hendrix  Rock    2700000  70000000.0
2     Miles Davis  Jazz    1500000  48000000.0
3             SIA   Pop    2000000  74000000.0

In [111]:
df.groupby('Genre').sum()

Listeners       Plays
Genre                       
Jazz     2800000  75000000.0
Pop      2000000  74000000.0
Rock     5400000  70000000.0

In [114]:
df['Avg Plays'] = df['Plays']/df['Listeners']
df

Artist Genre  Listeners       Plays  Avg Plays
0  billie Holiday  Jazz    1300000  27000000.0  20.769231
1    Jimi Hendrix  Rock    2700000  70000000.0  25.925926
2     Miles Davis  Jazz    1500000  48000000.0  32.000000
3             SIA   Pop    2000000  74000000.0  37.000000
4    Jimi Hendrix  Rock    2700000         NaN        NaN

# numpy

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.random.random(3)

array([0.32083828, 0.38898997, 0.42765302])

In [6]:
data = np.array([1,2])
data

array([1, 2])

In [7]:
ones = np.ones(2)
ones

array([1., 1.])

In [8]:
data + ones

array([2., 3.])

In [9]:
data * data

array([1, 4])

In [10]:
data / data

array([1., 1.])

In [11]:
data * 1.6

array([1.6, 3.2])

In [12]:
data = np.array([1,2,3])
data[1:]

array([2, 3])

In [13]:
data.max()

3

In [14]:
data.sum()

6

# In more dimensions

In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.random.random((3,2))

array([[0.55136644, 0.34143215],
       [0.48925516, 0.71299477],
       [0.05976628, 0.04384729]])

In [19]:
data = np.array([[1,2],[3,4]])
ones = np.ones([2,2])
data + ones

array([[2., 3.],
       [4., 5.]])

In [20]:
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([1,1])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [22]:
data = np.array([1,2,3])
powers_of_ten = np.array([[1,10],[100,1000],[10000,100000]])
data.dot(powers_of_ten)

array([ 30201, 302010])

In [23]:
data = np.array([[1,2],[3,4],[5,6]])
data[1:3]

array([[3, 4],
       [5, 6]])

In [24]:
data[0:2,0]

array([1, 3])

In [26]:
data.min()

1

In [25]:
data.sum()

21

In [34]:
data = np.array([[1,2],[5,3],[4,6]])

In [35]:
data.max(axis=0)

array([5, 6])

In [36]:
data.max(axis=1)

array([2, 5, 6])

In [44]:
data = np.array([[1,2],[3,4],[5,6]])
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [45]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [46]:
data.reshape(2,3)
data

array([1, 2, 3, 4, 5, 6])

In [47]:
data.reshape(3,2)
data

array([1, 2, 3, 4, 5, 6])

In [48]:
data = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
data

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [50]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
np.random.random((4,3,2))

array([[[0.70327192, 0.53951495],
        [0.92676896, 0.14004487],
        [0.20037286, 0.23525541]],

       [[0.719414  , 0.37060305],
        [0.10104047, 0.56074874],
        [0.51913687, 0.8760903 ]],

       [[0.01674602, 0.10035312],
        [0.29965283, 0.21572951],
        [0.88107101, 0.90988323]],

       [[0.68404285, 0.65193117],
        [0.18993568, 0.41156443],
        [0.8196785 , 0.93236361]]])

# MeanSquareError

In [53]:
n = 3
predictions = np.array([1,1,1])
labels = np.array([1,2,3])
error = (1/n) * np.sum(np.square(predictions - labels))
error

1.6666666666666665